### ISSUE TITLE
Cannot select the fake type when using pointers

### ISSUE THREAD

**Issue by zkynet** [bxcodec/faker#46]
Hey there, I am having trouble applying the faker:"Something" tag to struct fields that are pointers. 

Here is the struct: 
```javascript
type UserInput struct {
	FirstName         *string                 `json:"first_name,omitempty" faker:"first_name_male"`
	LastName          *string                 `json:"last_name,omitempty" faker:"first_name_male"`
	FullName          *string                 `json:"full_name,omitempty" faker:"first_name_male"`
	Email             *string                 `json:"email,omitempty" faker:"email"`
}
```

Stack:

panic: reflect.Set: value of type string is not assignable to type *string
```javascript
goroutine 1 [running]:
reflect.Value.assignTo(0x15f1b80, 0xc0001f6a60, 0x98, 0x16e569f, 0xb, 0x15e0520, 0x0, 0xc0001f6a60, 0x0, 0x0)
        /usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:2269 +0x44c
reflect.Value.Set(0x15e0520, 0xc000210640, 0x196, 0x15f1b80, 0xc0001f6a60, 0x98)
        /usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:1403 +0xa7
bitbucket.org/teammemento/demo-api/vendor/github.com/bxcodec/faker.setDataWithTag(0xc0000b6640, 0xc000210640, 0x16, 0x15f253e, 0xf, 0x16, 0x196)
        /Users/zkynet/go/src/bitbucket.org/teammemento/demo-api/vendor/github.com/bxcodec/faker/faker.go:311 +0x282
bitbucket.org/teammemento/demo-api/vendor/github.com/bxcodec/faker.getValue(0x17a2c20, 0x16ba440, 0x16ba440, 0x5, 0xc0002184f0, 0xc0000f7d18, 0x100dc0f)
        /Users/zkynet/go/src/bitbucket.org/teammemento/demo-api/vendor/github.com/bxcodec/faker/faker.go:209 +0x168b
bitbucket.org/teammemento/demo-api/vendor/github.com/bxcodec/faker.FakeData(0x161af20, 0xc0002105a0, 0x1d02880, 0x15d3c60)
        /Users/zkynet/go/src/bitbucket.org/teammemento/demo-api/vendor/github.com/bxcodec/faker/faker.go:152 +0x1f5
```

Now, if I remove the faker:"first_name_male" .. everything works fine. 

It probably has something to do with this change:
https://github.com/bxcodec/faker/pull/17/commits/d5d9f35bc27255714794d682d2163a65cd7cd531

Peace and love <3

**Comment by bxcodec** [comment]
Thanks for the issue, will investigate how to fix this soon.
For now, I think you can use without pointers.
